version: '3'

services:
  mongo:
    image: mongo
    tty: true
    volumes:
      - ./local/mongo:/data/db
    ports:
      - '27017:27017'
    restart: on-failure

  api:
    image: obs-api
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./_helpers:/opt/obsAPI/_helpers
      - ./_middleware:/opt/obsAPI/_middleware
      - ./accounts:/opt/obsAPI/accounts
      - ./config:/opt/obsAPI/config
      - ./data:/opt/obsAPI/data
      - ./models:/opt/obsAPI/models
      - ./logic:/opt/obsAPI/logic
      - ./public:/opt/obsAPI/public
      - ./routes:/opt/obsAPI/routes
      - ./app.js:/opt/obsAPI/app.js
    environment:
      - PORT=3000
      - MONGODB_URL=mongodb://mongo/obsTest
    links:
      - mongo
    ports:
      - '3000:3000'
    restart: on-failure
    command:
      - npm
      - run
      - dev
