version: '3'

services:
  mongo:
    image: mongo
    tty: true
    volumes:
      - ./local/mongo:/data/db
    ports:
      - '27017:27017'
    restart: on-failure

  api:
    image: obs-api
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./src:/opt/obsAPI/src
    environment:
      - PORT=3000
      - MONGODB_URL=mongodb://mongo/obsTest
    links:
      - mongo
    ports:
      - '3000:3000'
    restart: on-failure
    command:
      - npm
      - run
      - dev
